/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ui;

import de.fhdo.ewks.ml_example.ui.AbstractDataStructureLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DataStructureLanguageUiModule extends AbstractDataStructureLanguageUiModule {
  public DataStructureLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
