/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class DataStructureLanguageQuickfixProvider extends DefaultQuickfixProvider {
}
