/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.scoping;

import de.fhdo.ewks.ml_example.scoping.AbstractDataStructureLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DataStructureLanguageScopeProvider extends AbstractDataStructureLanguageScopeProvider {
}
