/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example;

import de.fhdo.ewks.ml_example.DataStructureLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataStructureLanguageStandaloneSetup extends DataStructureLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new DataStructureLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
