/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example;

import de.fhdo.ewks.ml_example.AbstractDataStructureLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataStructureLanguageRuntimeModule extends AbstractDataStructureLanguageRuntimeModule {
}
