/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.validation

import de.fhdo.ewks.ml_example.Structure
import org.eclipse.xtext.validation.Check
import de.fhdo.ewks.ml_example.Ml_examplePackage
import de.fhdo.ewks.ml_example.Context

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DataStructureLanguageValidator extends AbstractDataStructureLanguageValidator {
	@Check
	def checkStructureName(Structure structure) {
		if (!structure.checkName)
			error("Structure name must start with an uppercase letter",
				structure,
				Ml_examplePackage::Literals.STRUCTURE__NAME)
	}

	@Check
	def checkUniqueStructures(Context context) {
		val duplicateStructureIndex = context.checkUniqueStructures
		if (duplicateStructureIndex > -1) {
			val duplicateStructure = context.structures.get(duplicateStructureIndex)
			error('''Duplicate structure «duplicateStructure.name»''',
				duplicateStructure,
				Ml_examplePackage::Literals.STRUCTURE__NAME)
		}
	}
}
