/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataStructureLanguageScopeProvider extends DelegatingScopeProvider {
}
