/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ide


/**
 * Use this class to register ide components.
 */
class DataStructureLanguageIdeModule extends AbstractDataStructureLanguageIdeModule {
}
