/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ui.contentassist;

import de.fhdo.ewks.ml_example.ui.contentassist.AbstractDataStructureLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DataStructureLanguageProposalProvider extends AbstractDataStructureLanguageProposalProvider {
}
