/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DataStructureLanguageRuntimeModule extends AbstractDataStructureLanguageRuntimeModule {
}
