/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fhdo.ewks.ml_example.DataStructureLanguageRuntimeModule;
import de.fhdo.ewks.ml_example.DataStructureLanguageStandaloneSetup;
import de.fhdo.ewks.ml_example.ide.DataStructureLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DataStructureLanguageIdeSetup extends DataStructureLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    DataStructureLanguageRuntimeModule _dataStructureLanguageRuntimeModule = new DataStructureLanguageRuntimeModule();
    DataStructureLanguageIdeModule _dataStructureLanguageIdeModule = new DataStructureLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_dataStructureLanguageRuntimeModule, _dataStructureLanguageIdeModule));
  }
}
