/**
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.ide;

import de.fhdo.ewks.ml_example.ide.AbstractDataStructureLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DataStructureLanguageIdeModule extends AbstractDataStructureLanguageIdeModule {
}
