/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.parser.antlr;

import com.google.inject.Inject;
import de.fhdo.ewks.ml_example.parser.antlr.internal.InternalDataStructureLanguageParser;
import de.fhdo.ewks.ml_example.services.DataStructureLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DataStructureLanguageParser extends AbstractAntlrParser {

	@Inject
	private DataStructureLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDataStructureLanguageParser createParser(XtextTokenStream stream) {
		return new InternalDataStructureLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Context";
	}

	public DataStructureLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DataStructureLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
