/*
 * generated by Xtext 2.16.0
 */
package de.fhdo.ewks.ml_example.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DataStructureLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/fhdo/ewks/ml_example/parser/antlr/internal/InternalDataStructureLanguage.tokens");
	}
}
